apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: app1
spec:
  project: app1

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  source:
    repoURL: https://github.com/melethron/helm-charts.git
    targetRevision: HEAD
    path: charts/busybox

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
